name: Java CI

on:
  push:
    branches: 
      - gradle

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup wrapper
      run: gradle wrapper --gradle-version 6.0.1 & ./gradlew clean test 
        
      
