# Action uses gradle-command
# https://github.com/marketplace/actions/gradle-command
# Gradle 6 required for JDK 13
name: Java CI with JDK 13

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: test        
